name: Copy website to S3 and invalidate CloudFront Distribution

on:
  push:
    branches:
      - main

jobs:
  copy-website-to-s3-and-invalidate-cloudfront:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug Information
        run: |
          echo "Current working directory: $PWD"
          echo "List files in the current directory:"
          ls -al
          echo "Environment variables:"
          printenv
          echo "AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}"
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "DISTRIBUTION: ${{ secrets.DISTRIBUTION }}"

      - name: Inject their API Key into HTML
        run: |
          echo "Injecting API key into HTML file"
          sed -i "s/YOUR_PLACEHOLDER_KEY/${{ secrets.AWS_API_KEY }}/g" Resume challenge_updated_2024/shortenGPT.html


      - name: Sync S3
        uses: jakejarvis/s3-sync-action@v0.6.0
        with:
          args: --follow-symlinks --delete --exclude '.git/*' --size-only
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'Resume challenge_updated_2024'

  invalidate-cloudfront-distribution:
    needs: copy-website-to-s3-and-invalidate-cloudfront
    runs-on: ubuntu-latest
    steps:
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
